//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormDB1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetail
    {
        public string IBAN { get; set; }
        public string BIC { get; set; }
        public int CustomerID { get; set; }
        public int BankDetailNr { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
