//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormDB1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int ConnectionID { get; set; }
        public int ConnectionTypeID { get; set; }
        public int ConnectionNr { get; set; }
        public int CustomerID { get; set; }
        public string Connection1 { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ConnectionType ConnectionType { get; set; }
    }
}
